var dataList = [
  {
    question: "Developments in science and technology have caused environmental problems. Some people think that a simpler way of life will protect the environment, while others believe that science and technology can solve environmental problems. Discuss both views and give your own opinion.",
    keywords: "",
    sample: "<u>Although it is sometimes thought that</u> developments in science and technology have <b>a negative effect</b> on the environment. <u>other people believe that</u> science and technology are able to solve environmental problems.<u> In my opinion, I consider that</u> technology can cause environmental problems, but developments in science and technology can also solve them.<br/><br/><u>On the one hand, it is undeniable that</u> the rapid developments of technology have caused some environmental problems. Many <b>inventions</b> <u>are beneficial for</u> human beings, but they have a negative effect on the environment. <u>For example</u>, the invention of <b>cars</b> that use <b>fossil fuel</b> has caused some serious effect on the world. The cars produce <b>carbon monoxide</b> which is not only dangerous for living creatures, but it also becomes the main cause of <b>global warming</b>. <u>Therefore</u>, some people think that we should reduce using cars but using some <b>environmental transportations</b> such as using a bicycle to travel.<br/><br/><u>On the other hand, other people believe that</u> technology could be used as a way to solve environmental problems. Using the same car example, nowadays many countries are developing some friendly environmental cars such as <b>electric car</b> and some other <b>new energy cars</b>. These kinds of cars are using <b>green energy</b> such as <b>solar power</b> or <b>electric power</b>. Therefore, using these cars could save the environment and improve the lifestyle of human beings.<br/></br><u>In conclusion, I do believe that</u> technology is beneficial for human beings, although some inventions had caused environmental problems, with the development in science and technology, the new technology can solve the problems which were caused by <b>previous generation technology</b>."
  },
  {
    question: "The international community must act immediately to ensure that all countries reduce their consumption of fossil fuels, such as gas and oil. To what extent do you agree or disagree?",
    keywords: "",
    sample: "Increasing consumptions of fossil fuels <u>have resulted in</u> <b>the emission of the greenhouse gas</b> which is one of the causes of issues relating to <b>environmental damage</b> in recent years. Therefore, <u>some people suggest that</u> all countries should take actions urgently to lessen the usage of the harmful energy. <u>From my personal view, I agree with the statement to some extent.</u><br/><br/><u>First of all, it cannot be denied that</u> fossil fuel is one of the major contributors to <b>global warming</b> and <b>climate change</b>. Indeed, the burning of <b>oil</b> and <b>coal</b> produces tonnes of <b>carbon dioxide</b> per year, and it is one of the greenhouse gases that enhance <b>radioactive forcing</b> and contribute to global warming. <b>The rise in temperature of the Earth</b> has associated with numerous of adverse effects such as <b>melting of polar ice caps</b>, flooding of low-lying areas and <b>rise to the sea level</b>.<br/><br/><u>Secondly</u>, fossil fuels are generally considered to be <b>non-renewable resources</b> because they take millions of years to form. If the utilisation of mineral fuels is not reduced and controlled, it could be <b>exhausted</b> and people may soon run short of fossil fuels while scientists have not found an <b>alternative energy source</b>. <u>As a result</u>, the price of fossil fuels has also increased greatly which could lead countries to fall into a fuel war.<br/><br/><u>However</u>, there might be some concerns about the reduction of <b>mineral fuels utilisation</b>. One among of them is that the approach will lead to failure to maintain <b>well-balanced social order.</b> In fact, manufacture industry, transportation and even home heating require powers, which are generated through fossil fuels. Accordingly, detrimental consequences might impact to the development of the entire the world if we cut down the use of fossil fuel immediately. <u>More than that</u>, some alternative powers such as <b>nuclear</b>, <b>solar</b> and <b>wind power</b> have not been applied widely due to reasons like climate condition, high cost or safety requirement. It could take scientist many years developing these energies to be perfect substitutes for fossil fuel.<br/><br/><u>In conclusion</u>, in order to tackle environment problems and avoid the growing scarcity of natural energy in the future, the reduction in the consumption of fossil fuels should be considered and planned purposefully and gradually."
  },
  {
    question: "Some people think job satisfaction is more important than job security, while others believe that having a permanent job is better than enjoying the job. Discuss both views and give your own opinion.",
    keywords: "",
    sample: "<u>Although it is sometimes thought that</u> some individuals believe job satisfaction should be more important than job security. <u>Other people think that</u> a permanent job should be better than a satisfactory job. <u>In my opinion, I consider that</u> job satisfaction is an important factor in the work life, but job security is more important.<br/><br/><u>On the one hand, it is felt by many that</u> work which gives <b>self-satisfaction</b> should be opted rather than <b>a fixed job</b>. The primary reason for this belief is the health benefits including <b>physical health</b> and <b>mental health</b>. Working at a place which gives you pleasure not only helps to grow in the <b>professional field</b> but also helps to keep yourself healthy. <u>Therefore</u>, <u>it is obvious that</u> successful professional life can also <u>result in</u> the perfect personal life, <u>thereby</u> helping you to keep your family members happy.<br/><br/><u>On the other hand</u>, there are some people who consider <b>life-long employment</b> is necessary even if not fulfilled by the type of work. The main cause of believing this can be <b>the assurance of receiving a constant salary</b>. Usually, people need <b>regular income</b> for fulfilling their <b>daily needs</b> and a permanent job means a regular flow of money. <u>Hence</u>, <u>it is apparent that</u> human being will be able to satisfy his family needs, and can, therefore, live a happy satisfied life.<br/><br/><u>In conclusion</u>, it is believed that even though job satisfaction should be considered while accepting jobs, security is very much important for leading a comfortable and <b>stress-free</b> life."
  },
  {
    question: "Some people think vertical city is the best, where people live and work in tall buildings. Others think horizontal city is better, where there are few tall buildings. Discuss both these views and give your own opinion.",
    keywords: "",
    sample: "Undoubtedly, nowadays due to <b>shortage of land</b> and <b>increase in population</b>, skyscraper buildings are booming day by day in a city side, whereas in the countryside still many people prefer to live in a horizontal house. While, personally, in my point of view both have its own merits and demerits, which I will enunciate below.<br/><br/>To begin with, <u>there are no doubt</u> builders who construct the buildings buy a small land and to earn large profits, they construct the tall buildings at one go. In many countries, these kinds of buildings are eminent and used for office and living purpose because of shortage of land. <u>For instance</u>, I am staying in Hong Kong on the 29th floor and complete building has 35 floors. <u>Moreover</u>, nowadays people hold the opinion that all those people who stay on the higher floors are safe from <b>noise pollution</b> and <b>air pollution</b> compared to those who lives on the lower floors of the building. However, tall buildings have its own disadvantages such as in case of lifts predicament, it is really strenuous for everyone to use the staircase. Moreover, in case of fire, for example, it would be difficult and unsafe for <b>fire exits</b>.<br/><br/>On the other hand, some people prefer to live in horizontal buildings which have its own advantages. Firstly, there is no need to spend extra amount on <b>lifts</b> and <b>escalators</b>. Moreover, due to this there is saving on electricity bills, which in turn </b>save energy</b>. Secondly, the small house is safe in case of risks which are caused by natural calamities such as <b>earthquake</b>. Finally, a ventilation system is much better in the small buildings compared to high buildings.<br/><br/>To recapitulate, there is no doubt that tall building is equally important like small building due to scarcity of land. Nevertheless, both have its own <u>pros and cons</u> and it totally depends upon the place where buildings are constructed."
  },
  {
    question: "Some people think that success in life comes from hard work and determination, while others think that there are more important factors such as money and appearance. Discuss both views and give your opinion.",
    keywords: "",
    sample: "It is true that people have a lot of ways to <b>achieve success</b> in their life. While some people think money and appearance are two factors affecting to people's success, I would argue that people can reach a peak of their career when they work hard and have determination.<br/><br/><u>On the one hand</u>, there are several reasons why <b>finance and physical beauty</b> are important contributors to success in life. First reason is that money enables people <b>reaching their deep desires</b> like power and frame. For example, if people have a great deal of money, they have countless opportunities to progress rapidly in their career or <b>being well-known</b> in the community that they desired. <u>Furthermore</u>, personal appearance is one of the crucial factors impacting achievement. For instance, it would be a good chance for candidates to <b>seek a job</b> if they indicate their confident body posture or wearing clothing apart from great skills and experiences.<u>On the other hand</u>, it is undeniable that hard working and resolution are necessary features which are pivotal to ensure success. Firstly, hard work helps people <b>gain some valuable experiences</b> in aspects of life. For example, if young student practices several times some kinds of assignment in college and home, they are likely to minimize the risk of repeating the same mistakes so they have the tendency to get high scores in the formal exam. Secondly, determination gives us the <b>motivation to set up goals</b> which become the foundation of success. <u>As a result</u>, this is an <b>essential skill</b> to allow people <b>overcome the complex problems</b> in all situation and always keep moving forward to reach the <b>long-term goals</b>.<br/><br/><u>In conclusion</u>, although money and personal appearance have an influence on <b>achievement</b>, <u>it seems to me that</u> hard work and resolution are dominant factors to get the highest achievement."
  },
  {
    question: "Universities and colleges are now offering qualifications through distance learning from the Internet rather than teachers in the classroom. Do you think the advantages of this development outweigh the disadvantages?",
    keywords: "",
    sample: "<u>It is undoubted that</u> the appearance of distance education has <b>revolutionized the way of teaching and learning</b>. However, there remains a controversial issue on whether it is a more a blessing or a curse. <u>It is my personal belief that although the cons are inescapable, the benefits it brings to us generally outweigh the drawbacks</u>.<br/><br/>To begin with, <u>we have to admit that</u> <b>on-line education</b> do cause problems. Initially, for students who are <b>lack of self-control</b>, large possibilities are that <b>they will either indulge themselves in on-line games or will be distracted from on-line chat rooms without proper supervision from teachers</b>. Moreover, <b>individual learning</b> experience may make the young adults become <b>socially inadequate</b>, even isolated due to <b>the lack of face-to-face communications</b> with teachers and fellows.<br/><br/>However, <u>seen from the positive side</u>, certain virtues can be gained via distance education. First, distance education can provide a <b>more flexible schedule</b> for students to arrange their study plan more freely. This is especially suitable for special learning groups, such as part-time learners, sick students or self-learners. More importantly, <b>tele-education</b> is a <b>convenient and economical way of learning</b> -- students do not have to travel for long distances and pay for expensive tuition. Ultimately, it <b>shares the greatest teaching resources</b> in the world and provides equal chances for learners from any corner of the world, which will definitely help to <b>enhance the educational level</b> of humankind.<br/><br/><u>By way of conclusion</u>, distance teaching is a blessing brought by the progress of the Internet. However, it is better for us to take it as a <b>supplementary tool</b> of traditional teaching rather than a replacement and try to prevent or at least weaken its negative impact."
  },
  {
    question: "Nowadays, more and more jobs and task are done by machines which involve hard physical work. Do these effects of this trend outweigh the negative effects?",
    keywords: "",
    sample: "For centuries, people have fantasized that someday machines could have intelligence like mankind and work as faithful servants. Nowadays, it is common that more and more jobs and tasks which involve hard physical work are done by machines. Although some people believe the positive impacts of the tendency would far more than the negative ones, I believe the issue of the wide application of machines can be deemed as beneficial as detrimental.<br/><br/><u>On the one hand</u>, there is no denying that <b>hi-tech machines</b> bring about an array of positive aspects, such as <b>high work efficiency</b> and <b>low work risk</b>. First, the workload that could take months to finish by manual labor could be done flawlessly by machines in minutes, which allows individuals to be involved in other more meaningful and challenging activities. It means ordinary workers could have <b>more time and energy to enjoy their life</b>. Second, it is widely acknowledged that machines could substitute man for high-risk jobs, like <b>mining and construction</b>, which commonly involve hard physical work. By adopting machines in those work places, people’s safety can be ensured to a considerable degree.<br/><br/><u>On the other hand</u>, there are numerous demerits which should not be neglected. To begin with, more people may <b>lose jobs</b> or suffer great <b>layoff</b> pressure when machines take their places, especially in the mass production industry such as the automobile business. In factories of the famous car company Ford, almost every step of assembly line work is done by giant <b>robots</b> that work faster with higher reliability and precision. <u>As a consequence</u>, employees will suffer great pressure resulting from layoff. Besides, machines cannot work in a <b>flexible way as people do</b>, and they are less likely to <b>make corresponding changes</b> once something unexpected happens. If a <b>wrong code</b> runs in one machine, there may be thousands of defective products appearing on the production line.<br/><br/>Taking all factors into account, although machines have many merits that make our life easier and more convenient, the demerits should not be ignored as workers may be afflicted with unemployment stress and the number of inferior goods may be huge."
  },
  {
    question: "Some people think that with the increasing use of mobile phones and computers, people lose the ability to communicate face to face. To what extent do you agree or disagree?",
    keywords: "",
    sample: "People are more dependent on technology these days. With technology, people become less diligent and prefer to <b>do something in short and simple way</b>; communication for example. I agree that people will lose their ability to communicate with others face to face because the raise of technology such as computers and mobile phones. This will make people do more writing than speaking, thus their communication skill are sinking. <br/><br/>People who communicate through text and chat messenger on computers and mobile phones are used to do <b>more writing rather than speaking</b>. So that when they have a face to face conversation with someone, they will have <b>difficulty on expressing their idea directly</b> because as we write, we can fix our sentence by add some suitable words or delete inappropriate words. While speaking is more spontaneous, we cannot change the words that we spoke. Moreover, people are prefer to communicate with someone virtually because sometimes the people that we want to communicate with in person <b>are not as friendly as</b> they are in virtual chatting so when those two people meet, they will have an awkward moment. <br/><br/>On contrary, technology makes people <b>get closer easily</b> because we can still keep in touch with someone who live far miles away. With computers and mobile phones, we can communicate with people from different cultures and increase our communication skill by having conversation with them either through texting or video chatting. <br/><br/>In conclusion, I believe with more people communicating virtually using communication devices will endanger their ability to communicate with others face to face. Because it will makes people not used to express their idea spontaneously and correctly. "
  },
  {
    question: "People can live and work anywhere they want to choose because of improved communication technology and transport. Do the advantages of this development outweigh disadvantages?",
    keywords: "",
    sample: "It is irrefutable that because of the advances in <b>telecommunication technology</b> and travel, today’s person can live and work in any part of the globe. The advantages of this definitely outweigh the disadvantages. In the following paragraphs I shall put forth my arguments to support my views.  <br/><br/>There are many advantages of being able to live and work from anywhere. First of all, people have <b>more choices of jobs</b> because of technological advances. Not only can you work in any part of your home country, you can work for any company in any part of the world by telecommuting. Secondly, modern wireless technology has <b>made work easier and created more time for self and family</b>. What is more, people can lessen their work hours and still do their work <b>more efficiently</b>. Another advantage is that people can <b>manage more than one work at a time</b>. This is the need of the day as inflation is touching the sky and people need to earn more and more. <br><br>Furthermore, the modern transportation modes like the metro and light rail have <b>lessened the travel time</b> and also made it more convenient for commuters. This has also decreased the need for people to live in the cities to do jobs because now it is possible to work in cities and come back to peaceful countryside in the evenings because of modern transport systems. This has decreased the <b>overcrowding of cities</b> which was making cities unbearable to live in.<br><br><u>On the downside</u>, <u>this is leading to</u> <b>a sedentary lifestyle</b> as people don’t need to travel. Another disadvantage is that people become so <b>dependent on technology</b> that any network failure may lead life to come to a standstill. Nevertheless, I still believe that these minor disadvantages are of no importance if we look at the plethora of advantages this situation has to offer. <br><br><u>To put it in a nutshell</u>, I pen down saying that, people can live and work anywhere today and <u>this situation is more of a boon than a bane</u>."
  },
  {
    question: "In some countries many young people choose to work or travel for a year between finishing high school and starting university studies. Discuss the advantages and disadvantages.",
    keywords: "",
    sample: "Travelling seems to be an indispensable part of almost everyone’s life. It helps people <b>broaden their knowledge</b> as well as <b>improve their living skills</b>. Hence, many people recommend that students should travel after finishing high school and before entering university studies. In this paper, I’m going to discuss the advantages and disadvantages of this.<br><br>Firstly, travelling can help us to <b>improve our health</b>. When travelling, people tend to <b>do more outside activities</b> such as mountain climbing. Hence, it can help students have a better health which is good for their future study. Next, travelling gives us opportunities to explore the world. Going to different countries, you can study different cultures and how they are different from each other. Therefore, students can broaden their knowledge.<br><br><u>Despite the benefits</u>, travelling before starting a new degree in a university can make student <b>forget their academic knowledge</b>. For example, mathematics involves many formulas which are very hard to remember if students don’t keep practicing frequently. Moreover, students who travel like this tend to <b>have problems in re-adapting in an academic environment again</b>.<br><br>From my personal viewpoint, travelling after finishing high school and before entering university studies is beneficial even though there are many disadvantages. The reason is that it’s a requirement for all of us now to become qualified so that we find a good job. Therefore, people can still overcome the difficulties that I mentioned. "
  },
  {
    question: "Most of the urgent problems can only be solved with international cooperation.  To what extent do you agree or disagree？",
    keywords: "",
    sample: "What these days we know about critical issues around the world is that most of them need a global support for struggling with. According to some common aims between nations, I completely agree with this idea.<br><br>As we know, <b>globalization</b> is one of the most crucial and vital happenings for all countries. But, what states are concerned about is that how to tackle inevitable incidents such as <b>economic crises</b>, <b>global warming</b> or <b>greenhouse gasses emissions</b>. Regarding these <b>universal issues</b>, all governments know that these problems have the <b>worldwide impact</b> on our planet and their country and their individuals are involved. They appreciate that globalization has removed all borders and walls between countries. Therefore, I believe that addressing to these problems needs an international cooperation.<br><br>On the other hand, our world is confronting to some issues which do not belong to one nation or one district. I can point put to <b>HIVs</b>, <b>religious wars</b>, and <b>environmental issues</b>. Nowadays, our world is facing to lots of <b>terrorism</b>, especially, in the Middle East, there are many murders and bombing which need worldwide support and assistance. In addition, most of the environmental issues go back to <b>global deforestation</b> and it leads to global warming and increasing greenhouse emissions. What I intended to address the named crises is a controversial argument and all of them could not be solved by one country planning. As a result, I appreciated that eradicating international problem need an international cooperation.<br><br>In conclusion, regarding <b>globalization</b> and <b>international issues</b>, there is no alternative option to tackle and eradicate of them exception international cooperation."
  },
  {
    question: "Developing countries require help offered by international organizations to ensure healthy and sustainable development. Some people think that financial aid is important. Others believe that practical aid and advice is more important. Discuss both these views and give your own opinion.",
    keywords: "",
    sample: "International aid is considered significant as to bridge the gap between developing and developed countries. While I agree that poor countries need financial aid to go out of <b>poverty</b>, I believe practical aid and advice <b>play a more important role in</b> their development.<br><br>The major reason why developing countries are often in dire need of financial support is their <b>shortage of money</b>. With <b>direct donation</b> and <b>investment</b>, they can alleviate many <b>economic problems</b>. On the one hand, this can help poor people out of starvation. When people are provided with living basics of life, they are more likely to <b>receive education</b> and <b>acquire skills</b> to contribute to the country. On the other hand, foreign investment can be used for providing <b>public service</b> and <b>constructing infrastructure</b>. An improved social environment is instrumental in people’s sense of safety and their confidence in economic progress.<br><br>However, I think practical support and advice produce <b>long-term solutions</b> to their problems. Financial means can only offer a way to survive for the time being, but international organizations are unlikely to take care of poor people with an unlimited source of funding. Also, financial aid also tend to reduce poor people’s initiative to better themselves. <u>In contrast</u>, teaching them <b>how to make money by themselves</b> is a more constructive way than giving money directly. Programmes like <b>sending experienced professionals</b>, <b>training</b> local workers and <b>introducing advanced technologies</b> can create a more productive and independent workforce with a <b>long-lasting impact</b> on the economy. Additionally, <b>proper advice and guidance</b> are likely to avoid the <b>misuse of financial aid</b>.<br><br>To conclude, international organizations should prioritize practical support and advice over financial aid in order to help developing countries gain a healthy and sustainable development."
  },
  {
    question: "Advertising discourages people from being different individuals by making us all want to do the same and look the same. To what extent do you agree or disagree?",
    keywords: "",
    sample: "Advertising is a creative industry and a key part of modern business notwithstanding, some people argue that advertising influences the personal features of a man by <b>standardizing</b> a model that everyone wants to become; thus, there is no difference among individuals in society. I strongly disagree with this statement for some reasons below.<br><br>Firstly, different person has totally different tastes about one <b>style</b>, <b>trend</b>, or <b>item</b>. Therefore, one fashion trend may be encouraged but in one look, there could be several versions. For example, short hair is a trend in many fashion magazines but still, a woman can choose different styles such as black short hair, red curly one, or straight bob hair. The private characteristics of a person make the same trend specially and individuals choose the suitable style to reflect himself.<br><br>Secondly, advertisement accesses customer directly so that it brings everyone <b>more choices</b>. Without advertising we would have less choice by <b>lacking information of the products</b>. It is common that every line of a product has its own advertisement to bring it quickly to customers. For one item such as a watch, Casio which is a watch company has several advertisements for G-shock model for sporty people, dedication leather style for ladies and so on. Another example for sport shoes, people can decide which shoes fit them by watching advertisements of Nike, Skechers, New Balance.<br><br>To sum up, despite there exist some opinions about the identical effect of advertising on personal appearance of a man, I strongly believe that advertising could not make the difference of individuals disappear. In contrast, it brings human more choices and boosts various styles of a man."
  },
  {
    question: "The government should spend money in promoting sport and art in school, rather than sponsoring professional sports and art events in communities. To what extent do you agree or disagree?",
    keywords: "",
    sample: "One of the government duties and responsibilities is to pour its funds to the area of sports and art which can add spice to people’s life. The discussion centers on whether the <b>fund</b> should be allocated to campus sport and art or to the professional counterparts in communities. From a more holistic point, I am in favor of the view that social sports and art events are supposed to receive more government financial aid.<br><br>If governments spend more <b>grants</b> in professional sports and events, the value and benefit of sports and arts can be appreciated by more public. A larger number of people ranging from the sports enthusiasts and art fans can be found in communities and the well-funded sports and art events can cater for their needs and bring them more physical and mental enjoyment. Therefore, the core value presented by sports and arts can be better realized and admired by the public. By comparison, sport and art in school are in the subordinate place, which are usually regarded as pastime by most students and teachers.<br><br>The sports and art events in community can also <b>boost communication and interaction</b> in neighborhood. People tend to go out their doors to view or participate in the various sports or arts events if the government pours more money into communities. And they can share their understanding when enjoying the work of art or cultivate a sense of belonging when taking part in sports events.<br><br>On the other hand, sport and art events in school are also worth government attention. Schools are usually short in funds and the financial assistance from government can make school life more diverse and colorful. However, the fund allocated to schools can generate fewer benefits and other non-government organizations can donor some amount of money to meet the requirement.<br><br>To conclude, the government should sponsor the sports and art activities in community even if schools are also in need of financial support."
  },
  {
    question: "Some people say government should give the health care the first priorities, some others believe there are more important priorities to spend the tax payers' money. Discuss both views and give your opinion.",
    keywords: "",
    sample: "People hold the different views whether <u>the national authorities should allocate the state budget on</u> healthcare service or other priorities to comfort the citizens’ lives. Both sides of the argument will be discussed in this essay.<br><br><u>It is undeniable that</u> providing free medical services from the government is a must as its necessity to reduce the burden for the country’s residents. Coping with the fast-paced life, many people suffer from some certain diseases caused from the workplace and lifestyle. This leads to a great amount of money spent on medicine and medical treatment. For instance, an <b>increasing number of patients</b> need the medical care to treat the stress from work in the UK, therefore, National Health Care Service has been established to provide them free-of-charge healthcare.<br><br>There are, in fact, <u>other social issues needed to take into account</u>, and schooling is one of them. If the state could provide a free access to education, the people would have a better chance to facilitate their future with a good career prospect and the country itself could minimize the illiteracy. Many researchers have proven that the country, which has a well-trained labor force, has had the high standard of living, and therefore, been prosperous. Take Vietnam is as an example for this, although studying is not free but affordable, many Vietnamese graduates now can join in a multinational companies to earn their livings with higher wages. It is not exaggerate to say Vietnam has become a good nation to live and work both locals and expats recent years.<br><br>To sum up, receiving healthcare support from the government is the ultimate priority as the benefits it brings, but in my point of view, the country <b>should balance its budget between</b> medical care and education."
  },
  {
    question: "The government has the duty to ensure that its citizens have a healthy diet, while others believe this is individuals' responsibility. Discuss both views and give your opinion.",
    keywords: "",
    sample: "It is common for citizens in a modern society that suffer from a series of health problems. Some people believe that the government should <u>shoulder the obligation</u> to ensure its citizens to have healthy diets. Others claim that individuals should <u>take responsibilities for</u> their own healthy diets. I suppose having healthy diets needs <u>efforts both from</u> the government and individuals.<br><br>To begin with, <u>we have to admit that</u> the government has the duty to encourage its citizens to have a healthy diet, as it is the administrator of the country. Ensuring that every citizen has a healthy diet needs <b>large investment and long-term efforts</b>, which may be beyond the capacity of private companies. Meanwhile, the government can carry out some policies to encourage citizens to have healthy diets, which may be more persuasive. Moreover, the government can get <b>easy access to media</b>, and the policies can be easily publicized all around the country, which would arouse public awareness of having healthy diets.<br><br>At the same time, <u>we should not ignore the efforts of</u> individuals. If every individual can resist the temptation of unhealthy diets, there will be a large step in the country. For instance, people can <b>eat less fast food</b> which contains a huge quantity of oil and <b>calories</b>. Moreover, citizens should learn to balance their diet which is beneficial to their health. For example, they need to eat more fresh vegetables and fruit filled with <b>vitamin C</b>, which is good for people’s health.<br><br>Overall, it is necessary for the government to take responsibilities for citizens’ healthy diet. Meanwhile, individuals have the duty to pay more attention to their diets, which have significant effects on their health."
  },
  {
    question: "The increase in food production owes much to fertilizers and better machinery, but some people think that it has a negative impact on human health and community. To what extent do you agree or disagree?",
    keywords: "",
    sample: "<u>There is no denying that</u> the increase of food production depends on fertilizers and advanced machinery. However, some people believe that could have <b>adverse effects on</b> people’s health and the environment. From a point of view, fertilizers and machinery could affect people’s health and the society <u>to some extent</u>.There are many fertilizers especially <b>chemical fertilizers</b> which are used in growing crops in order to increase the production of food, which could <b>influence</b> people’s health and the environment. Because if the chemical fertilizers beyond the toleration of lands, they may flow into rivers around lands. People could suffer diseases when they drink these water. Furthermore, there are many fertilizers on the surface of vegetables and fruits. If people do not wash clear these food before they eat, they may get sick as well. Besides, chemical fertilizers can <b>erode</b> lands and <b>make lands become acid</b>, which could <b>reduce lands’ qualities</b>.<br><br>As a general rule, automated machines can substitute humans to do some farm works and it can <b>enhance productivity</b>. Admittedly, labour-replacing machinery could result in <b>the increase of unemployment</b> because machines can replace some farmers. For example, in the past, one land needed ten farmers to plant crops. But currently it only need one people and some machines to finish it. Even though the technology advances can boost the production of food, it also can increase the unemployment rate.<br><br><u>In a nutshell</u>, fertilizers and machinery have some disadvantages indeed, but these can influence the environment, people’s health and the unemployment rate."
  },
  {
    question: "Some people believe that computers and internet carry more weight than traditional education in children’s study. Some others believe that traditional schooling and teachers are still essential and more effective. Discuss the both viewpoints and give your own opinion.",
    keywords: "",
    sample: "People have differing opinions of whether <b>innovative technological devices</b> and the internet are more beneficial to children’s learning than traditional methods. While a group of commentators state that orthodox teaching should be paid attention to education, I believe that the implement of modern teaching strategies can bring more advantages to young learners.<br><br>There are a variety of reasons elucidating why conventional teaching is not replaceable. It is evident that traditional schooling has been employed for a long period of time, <b>established by professional and reliable educators who put a lot of effort into education systems</b>. Due to this fact, students’ needs are well catered by these experts. In addition, teachers are capable of individually providing students with effective instructions. This is because educators gain a rich range of experience in teaching. For example,preschool teachers in Taiwan are required to complete at least 6 months placement for the consolidation of teaching skills and pedagogical training such as curriculum design or lesson plans before the following application of teacher registration.<br><br>However, I argue that the innovation of technology is more likely to benefit students. Firstly, the inspiration of unique ideas and the <b>development of creative thinking skills</b> for young learns ensue from the use of the internet. To be more specific, students’ massive potential can be evoked by accessing the internet. Additionally, the newest gadgets can improve the learning environment. <b>Student who live in rural areas</b>, in particular, have a rich range of possibilities of conducting experimental research by utilising advanced tools such as 3D printers or computers in school laboratories.<br><br>In conclusion, although individuals indicate the importance of traditional teaching, I believe the use of technology can lead more benefits to education. (<b>supplementary</b>)"
  },
  {
    question: "Some people say that arts subject such as painting or drawing should not be made compulsory for high school students. To what extent do you agree or disagree?",
    keywords: "",
    sample: "That the subjects should be essential in curriculum at school has controversial. Several people believe that some art courses such as painting and drawing <u>ought not to forced to</u> learn at high school. I <u>partly agree with this opinion</u>.<br/><br/>To begin with, these classes <b>do not provide the important knowledge</b> for pupils, so it is <b>time-consuming</b> for students who do not fond of studying them. In detail, attending an art class is simply <b>in form of entertainment</b>, therefore a lot of students want to spend this time on receiving necessary lessons instead of drawing a picture or singing a song. Moreover, that art classes are compulsory for students sometimes <b>affect on the result</b>. For instance, some students have good mark on science subjects like math, biology but they <b>do not have talent to perform arts</b>, the final result of these students are not appreciated.<br/><br/>Nevertheless, there are some benefits in providing art lessons on both schools and students. Firstly, art classes increase the impacts among the members of the class. It is also known as a method to <b>mitigate the pressure</b> for students after tighten period. In addition, it is a good way to <b>discover the talents</b> in art section. For example, according to one art class, the school can recognize the students who have ability to draw the nice pictures and develope this skill. One more thing, the students can <b>improve the imagination</b> and have the opportunities to make the creative things.<br><br>In conclusion, although there are some advantages on studying art classes, students should have options to chose whether they ought to learn art subjects or not. High schools can put them into <b>optional category</b> to develope abilities and interest of the students."
  },
  {
    question: "In some countries, secondary schools aim to provide a general education across a range of subjects. In others, children focus on a narrow range of subjects related to a particular career. Which do you think is appropriate in today’s world?",
    keywords: "",
    sample: "Although most children today enjoy the right to receive education, <u>it is not within their power to decide</u> what subjects they may study at school.  Regarding this matter, educational theorists still find themselves at loggerheads over whether secondary schools should impart knowledge of various fields, or they should concentrate on teaching only a few selected subjects relating to a certain sphere of education. From my perspective, I reckon that secondary educational content should be narrowed down for students.<br><br><u>First of all</u>, a fewer choice of subjects to study at school will create a window of opportunity for students to blossom socially. <u>To further explain this</u>, students will not constantly find themselves in a battle against time trying to complete their homework, to prepare for new lessons or to review for upcoming exams. Instead, they will have more spare time to spend outdoors, to be with their friends or just to be with themselves. In this way, their self-confidence or communication skills will be boosted significantly.<br><br>It has been found that secondary students nowadays are feeling more stressed and overwhelmed than ever before, and the reason to explain this is quite self-explanatory. Many children today consider their schools prisons and their teachers correctional officers who would not stop giving them dull assignments to complete. When the inspiration to study is almost non-existent, it is understandably difficult for the students to keep a good performance at school. Consequently, the quality of education, on the whole, will go downhill.<br><br><u>To conclude</u>, I <u>hold the firm belief that</u> the schools should focus on a small choice of practical subjects so that the lives of secondary students should not be fettered down by any undue responsibility.  "
  },
  {
    question: "Because of traffic and housing problems in the cities，the government encourages businesses to move to the rural area. Do you think the advantages outweigh the disadvantages?",
    keywords: "",
    sample: "Industries and businesses are mostly situated in city areas and problems associated with this bring up the idea of moving the industries and enterprises from the big cities to the countryside. I believe this action will be a good solution for some major problems. This step will offer far more benefits than the disadvantages it has. Moving big industries, factories and other offices to regional areas has few disadvantages like transportation scarcity, the cost of rebuilding and finding new employees but this shift will <u>offer significant benefits</u> both for the city and rural people.<br><br>Firstly, moving the industries from city to rural areas is <b>a herculean task</b>. Furthermore, the financial concern is also important. For instance, <b>re-establishing business</b> in a regional area needs more money, and time. In addition, <b>transportation facility</b> in rural areas will be another concern for many businesses. Again, <b>most of the employees</b> in a current factory will not move to the rural area and that would make it difficult to move a running factory to a regional area.  Finally, industries will diminish the tranquillity in the rural area by <b>polluting</b> the environment and resulting extinction of flora and fauna in the village areas.<br><br>However, moving industries and other enterprises to the countryside from the cities will reduce the major problems like <b>pollutions</b>, <b>traffic jams</b>, <b>housing problems</b> and <b>crimes</b> in many cities. This will also <b>create more job opportunities</b> in the country sides. Moreover, <b>the transportation facilities will improve</b> in rural areas and <b>city life will get relief</b> from the choking traffic. In addition to this, <b>the living standard of the rural areas will be upgraded</b> with demanding educational and health services. Over population is a major concern for many cities and the decentralisation would be a great step to reducing the population ration in cities. Furthermore, in many cases, a country’s economic development relies on the development of the rural area and this step will ensure proper development of the rural area. Industries, factories and other big businesses are the main reasons many cities are polluted and the shift would ensure a healthy living place in city areas.<br><br><u>After considering both sides</u>, moving the industries to the countryside is a <b>long-term task</b> but it will ensure <b>the equal distribution</b> of population and facilities throughout the country. I hope this action will alleviate the perilous condition of city life as well as will help the rural area to develop faster."
  },
  {
    question: "Interviews form the basic selecting procedure for most large companies. However, some people think an interview is not a reliable means of choosing who to employ and there are some other better methods of selection. To what extent do you agree or disagree?",
    keywords: "",
    sample: "<b>Recruiting</b> new employees can be a long and painful process. The success of any business or organisation depends on the quality of its staff. Some employers conduct interviews to select new workers. I agree with the given statement which says that there are various other approaches. This essay intends to analyze methods of hiring new employees.<br><br><u>Undoubtedly</u>, an interview is an important method of <b>recruitment</b>. If selection has to be done merely on an interview, then the interview has to be well executed. It requires a detailed understanding of the organizational needs as well as a careful grasp of the prospective employees’ responses. It is not an easy task. If the recruitment is small scale and only a few employees are needed, it can prove fruitful otherwise alternative methods to hire have to be taken into account.<br><br>There are many other methods, which can be employed to hire new personnel. These hiring methods are a combination of several step-by-step tests. Initially, job vacancies are advertised, after which the recruiters <b>select resumes</b>, which meet the basic requirements for that particular job position. Then the <b>written test</b> is conducted to judge the skills and knowledge of the person. This is followed by <b>group discussions</b> and some other skill tests. Then the shortlisted candidates are <b>interviewed</b>. After this, <b>background checks</b> and <b>reference checks</b> are done of those shortlisted after the interview. It is important to check the credit record and criminal record. The reference checks are done to ascertain the authenticity of what is written in the resume. Finally, the selected candidates are sent for a <b>health check</b> to rule out any communicable diseases.<br><br>Analyzing the above mentioned methods it can be seen that no single method is perfect. Each job has its own requirements. Some jobs require qualification and some require experience. Big companies have a department devoted to <b>human resources</b>, which takes care of the hiring issues, but for small businesses finding the right employees at the right times can be an especially time-consuming and frustrating struggle. <b>External recruitment agencies</b> can be assigned the task of searching suitable candidates for jobs, but it may be very expensive. However, I believe that spending on the recruitment of new employees can prove to be a good investment, as good employees can breathe new life into your business.<br><br>To sum up, it can be reiterated that finding suitable employees is an arduous task and has to be a combination of written tests, group discussions, interviews and reference checks."
  },
  {
    question: "Nowadays, most people learn academic study in university, but others think we should encourage to learn vocational skills more, do you agree or disagree?",
    keywords: "",
    sample: "In the modern life, some people claim that students should learn job training programs instead of academic courses in university. While it is true that vocational skills are essential for students to some extent, I believe focusing on academic study in university brings more benefits.<br><br><u>To begin with</u>, there are several reasons why students should participate in vocational training courses. Firstly, students who attend job training classes can focus on their <b>interest</b> and <b>the subjects which is relative to their career</b> in future. For example, when students have passion for becoming electricians, it is necessary for them to learn about assembling electric circuit rather than philosophy in the universities. This helps them to save tuition fees significantly and have more time for their dream. Secondly, since job candidates from vocational training schools have been taught about job-related skills, they can <b>secure well-paid job quickly</b>. Therefore, their family’s financial burden can be greatly reduce and they can support their parents with better life quality.<br><br>However, I would argue that we can never ignore the immense value of academic study in universities. First, as <b>colorful campus life</b> can bring more wonderful experiences to students, they can develop comprehensively with <b>a wide range of knowledge</b> not only about specialized skills but also about other skills such as communication in business, public speaking and cross-cultural management. This allows them to meet the demand of multi-cultural workplace in the large corporations. Additionally, students who receive university education have access to <b>rich knowledge</b> and <b>manifold techniques</b>, they have lots of chances for <b>advancement in their career</b>. For instance, employees with bachelors degrees are likely to be selected for <b>higher position</b> than others who do not have.<br><br>In conclusion, while job training is necessary for students, I believe that academic study in university play an crucial role in student’s development."
  },
  {
    question: "In some countries, the role of a mother differs in some ways from the role of a father. Why do you think these differences exist? How might parental roles develop in the future?",
    keywords: "",
    sample: "It is true that there is a significant difference between the parental role of fathers and mothers. There are several reasons for this difference, and it will experience significant changes in the future.<br><br>The difference between the roles of fathers and mothers can be explained in several ways. The first reason lies in the conventional thinking of people. Although <b>gender equality</b> is widely accepted, many people in Asian countries still hold the belief that men are <b>breadwinners</b> and women are <b>homemakers</b>. In these countries, women still have fewer job opportunities and earn significantly less than their male fellows. As a result, they might have to sacrifice their career to take care of the family. <b>Gender difference</b> may be another reason. As men tend to be more strict and rational, they may teach their children to work hard and hold big ambitions. By contrast, women are soft, tender and get on well with others, so that children can learn to collaborate and develop social skills from them. Also, due to their <b>characteristics</b>, mothers often pay more attention to family and spend more time for children, while fathers often focus on making profits that support the family.<br><br>However, the current difference in parent roles of father mother will be lessened in the future. Firstly, the progress of <b>equal rights</b> has enabled women to take high positions in firms, so that they can earn more and become the breadwinners in their family. Meanwhile, as it is acceptable for men to leave their job to raise children, there will be more male homemakers in the future.<br><br>In conclusion, there are several factors that contribute to the difference in the roles of fathers and mothers, and this difference will be lessened in the near future."
  },
  {
    question: "Some people say that playing computer games is bad for children in every aspect. Others say that playing computer games can have positive effects on the way children develop. Discuss both views and give your opinion.",
    keywords: "",
    sample: "Nowadays, children spend several hours for playing video games which have become increasingly popular recently . While some people believe that playing computer game would be harmful , some others think that computer games may help the development of children in many ways. This essay shall consider both perspectives.<br><br><u>On the one hand</u>, there are several <u>negative impacts on</u> children if they keep playing computerized game in a long period. An immature child <b>is highly addicted to</b> the feeling of going through next levels of a game or boosting score to break a record. This type <b>addiction</b> can also cause some problems with their school , a lack of sleep or unfinished homework are consequences of spending for a few more hours on the computer. Moreover, children tend to stay quite at the same place for playing electronic games instead of working out having the high risk of obesity.<br><br>On the other hand, computer games can be both <b>entertaining</b> and <b>educational</b>. Users are often more enthusiastic and eager with <b>the virtual world</b> than the real one. These games encourage <b>imagination and creativity</b> , as well as <b>concentration</b>, <b>logic thinking</b> and <b>problem solving</b>, which are useful skills in real life. To specific, in shooting games, the character may run and shoot simultaneously which help children think quickly and develop their hand-eye coordination and users’ motor skills.<br><br>In conclusion, playing computers games has many advantages and disadvantages. Children are easily affected by electronic games , therefore, parents should assist them to choose the right games and ensure that they are not spending their entire day in front of the computer."
  },
  {
    question: "次重点预习范围：",
    keywords: "",
    sample: ""
  },
  {
    question: "In some countries there is not enough recycling of waste materials (e.g. paper, glass and cans). What are the reasons and solutions?",
    keywords: "",
    sample: ""
  },
  {
    question: "It has been suggested that all young adults should be required to undertake a period of unpaid work helping people in the community.  Would the drawbacks be greater than benefits to the community and the young adults themselves?",
    keywords: "",
    sample: ""
  },
  {
    question: "More and more people want to study at university, so competition of university places is increasing. Why more and more people want to study at university? Is it positive or negative?",
    keywords: "",
    sample: ""
  },
  {
    question: "Many countries believe that international tourism has harmful effects. Why do they think so? What can be done to change their views?",
    keywords: "",
    sample: ""
  },
  {
    question: "Some people think that only the best students should be rewarded. Others, however, think that it is more important to reward students who show improvements. Discuss both these views and give your own opinion.",
    keywords: "",
    sample: ""
  },
  {
    question: "Older people who need employment have to compete with younger people. What problem does this cause and what are the solutions？",
    keywords: "",
    sample: ""
  },
  {
    question: "Some people think that using mobile phones and computers has a negative effect on young people's reading and writing skills. To what extent do you agree or disagree?",
    keywords: "",
    sample: ""
  },
  {
    question: "Some working parents believe childcare centers can provide best care for children, while others think family members like grandparents can do it better. Discuss both views and give your opinion.",
    keywords: "",
    sample: ""
  },
  {
    question: "Some people think it is more important to plant more trees in open area in towns and cities than provide more housing.　To what extent do you agree or disagree?",
    keywords: "",
    sample: ""
  },
  {
    question: "The use of mobile phone is as anti-social as smoking. Since smoking is banned in certain places, using mobile phone should be banned as well. To what extent do you agree or disagree?",
    keywords: "",
    sample: ""
  },
  {
    question: "Some people think that the best way to improve road safety is to increase the minimum legal age for driving a car or motor-bike. To what extent do you agree or disagree?",
    keywords: "",
    sample: ""
  },
  {
    question: "Most of leaders and directors of organizations are older people. Some people think it is better to have young people for these positions. To what extent do you agree or disagree?",
    keywords: "",
    sample: ""
  },
  {
    question: "Some people think most crimes are the result of circumstances like poverty and other social problems. Others believe that they are caused by people who are bad in nature. Discuss both views and give your opinion.",
    keywords: "",
    sample: ""
  },
  {
    question: "It is not necessary for people to travel to other places to learn about the culture. We can learn as much as from books, films and the Internet. To what extent do you agree or disagree?",
    keywords: "",
    sample: ""
  },
  {
    question: "Government funding should only be provided for the best students as scholarships. Other funding of universities should come from student fees and private organizations. To what extent do you agree or disagree?",
    keywords: "",
    sample: ""
  },
  {
    question: "Some people think that the governments of developing countries should introduce new technology to improve the quality of life, while some people believe that the best way is to develop education. Discuss both views and give your opinion.",
    keywords: "",
    sample: ""
  },
  {
    question: "The major cities in the world are growing fast and many problems occur. What are the problems that young people live in cities are faced with？ What solutions do you suggest？",
    keywords: "",
    sample: ""
  },
  {
    question: "Some people think that the government should ban dangerous sports, but others think that people should have the freedom to choose sports activities. Discuss both views and give your opinion.",
    keywords: "",
    sample: ""
  },
  {
    question: "Some countries achieve international success by building specialized facilities to train top athletes instead of providing sports facilities that everyone can use. Do you think it is a positive or negative development？",
    keywords: "",
    sample: ""
  },
  {
    question: "Some people think adults should learn practical skills by themselves, while others think they should learn from teachers in the classroom. Discuss both views and give your own opinion.",
    keywords: "",
    sample: ""
  },
  {
    question: "Many young people leave school with a negative attitude towards learning. What are the reasons and how can we encourage them to study?",
    keywords: "",
    sample: ""
  },
  {
    question: "Some people think that children can learn efficiently by watching television. Therefore, children should be encouraged to watch TV both at school and at home. To what extent do you agree or disagree？",
    keywords: "",
    sample: ""
  },
  {
    question: "Employers should give its staff at least four weeks of holidays a year to make employees do better in their jobs. To what extent do you agree or disagree?",
    keywords: "",
    sample: ""
  },
  {
    question: "In many countries today, both men and women need to work full time. Therefore, some people think men and women should share household tasks equally (e g. cleaning and looking after children). To what extent do you agree or disagree?",
    keywords: "",
    sample: ""
  },
  {
    question: "Some think that printed books are not necessary in the digital era, because all writing can be stored electronically. Others think printed books still play an important role. Discuss both views and give your own opinion.",
    keywords: "",
    sample: ""
  }
];